<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>DrawingArea</name>
    <message>
        <source>Copy</source>
        <translation>复制</translation>
    </message>
    <message>
        <source>Cut</source>
        <translation>剪切</translation>
    </message>
    <message>
        <source>Delete</source>
        <translation>删除</translation>
    </message>
    <message>
        <source>Layer</source>
        <translation>层级操作</translation>
    </message>
    <message>
        <source>Move Shape To Top</source>
        <translation>移动到顶层</translation>
    </message>
    <message>
        <source>Move Shape To Bottom</source>
        <translation>移动到底层</translation>
    </message>
    <message>
        <source>Move Shape Up</source>
        <translation>上移一层</translation>
    </message>
    <message>
        <source>Move Shape Down</source>
        <translation>下移一层</translation>
    </message>
    <message>
        <source>Paste</source>
        <translation>粘贴</translation>
    </message>
    <message>
        <source>Select All</source>
        <translation>全选</translation>
    </message>
    <message>
        <source>flow chart</source>
        <translation>流程图</translation>
    </message>
    <message>
        <source>SVG file generated by flowchart designer</source>
        <translation>流程图绘制器生成的SVG文件</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <source>Flowchart Designer</source>
        <translation>流程图绘制器</translation>
    </message>
    <message>
        <source>Start</source>
        <translation>开始</translation>
    </message>
    <message>
        <source>Arrange</source>
        <translation>排列</translation>
    </message>
    <message>
        <source>Export and Import</source>
        <translation>导入和导出</translation>
    </message>
    <message>
        <source>San Francisco</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>20 px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>24 px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>32 px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>40 px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>64 px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>B</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bold</source>
        <translation>加粗</translation>
    </message>
    <message>
        <source>I</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Italic</source>
        <translation>斜体</translation>
    </message>
    <message>
        <source>U</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Underline</source>
        <translation>下划线</translation>
    </message>
    <message>
        <source>Font</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Center</source>
        <translation>居中</translation>
    </message>
    <message>
        <source>Left</source>
        <translation>左对齐</translation>
    </message>
    <message>
        <source>Right</source>
        <translation>右对齐</translation>
    </message>
    <message>
        <source>Fill</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Opacity:</source>
        <translation>透明</translation>
    </message>
    <message>
        <source>Line</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Width:</source>
        <translation>宽度</translation>
    </message>
    <message>
        <source>0px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>0.5px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>1px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>1.5px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>2px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>3px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>4px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>5px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>6px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>8px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>10px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Style:</source>
        <translation>线条类型</translation>
    </message>
    <message>
        <source>Solid</source>
        <translation>实线</translation>
    </message>
    <message>
        <source>Dash S</source>
        <translation>短虚线</translation>
    </message>
    <message>
        <source>Dash L</source>
        <translation>长虚线</translation>
    </message>
    <message>
        <source>Dash</source>
        <translation>横点线</translation>
    </message>
    <message>
        <source>Page Setup</source>
        <translation>页面设置</translation>
    </message>
    <message>
        <source>Move Shape To Top</source>
        <translation>移动到顶层</translation>
    </message>
    <message>
        <source>Move Shape To Bottom</source>
        <translation>移动到底层</translation>
    </message>
    <message>
        <source>Move Shape Up</source>
        <translation>上移一层</translation>
    </message>
    <message>
        <source>Move Shape Down</source>
        <translation>下移一层</translation>
    </message>
    <message>
        <source>Export PNG</source>
        <translation>导出为PNG</translation>
    </message>
    <message>
        <source>Export PDF</source>
        <translation>导出为PDF</translation>
    </message>
    <message>
        <source>Export SVG</source>
        <translation>导出为SVG</translation>
    </message>
    <message>
        <source>Import SVG</source>
        <translation>从SVG导入</translation>
    </message>
    <message>
        <source>Select Font Color</source>
        <translation>选择字体颜色</translation>
    </message>
    <message>
        <source>Export as PNG</source>
        <translation>导出为 PNG</translation>
    </message>
    <message>
        <source>PNG Images (*.png)</source>
        <translation>PNG 图片(*.png)</translation>
    </message>
    <message>
        <source>Export Successful</source>
        <translation>导出成功</translation>
    </message>
    <message>
        <source>Flowchart has been exported to PNG image successfully!</source>
        <translation>流程图已成功导出为PNG图片！</translation>
    </message>
    <message>
        <source>Export Failed</source>
        <translation>导出失败</translation>
    </message>
    <message>
        <source>An error occurred while exporting the PNG image. Please check the file path and permissions.</source>
        <translation>导出PNG图像时出错。请检查文件路径和权限。</translation>
    </message>
    <message>
        <source>Export as SVG</source>
        <translation>导出为SVG</translation>
    </message>
    <message>
        <source>SVG Files (*.svg)</source>
        <translation>SVG文件(*.svg)</translation>
    </message>
    <message>
        <source>Flowchart has been exported to SVG vector image successfully!</source>
        <translation>流程图已成功导出为SVG矢量图像！</translation>
    </message>
    <message>
        <source>An error occurred while exporting the SVG file. Please check the file path and permissions.</source>
        <translation>导出SVG文件时出错。请检查文件路径和权限。</translation>
    </message>
    <message>
        <source>Import from SVG</source>
        <translation>从SVG导入</translation>
    </message>
    <message>
        <source>Confirm Import</source>
        <translation>确认导入</translation>
    </message>
    <message>
        <source>Importing SVG will clear all content on the current canvas. Do you want to continue?</source>
        <translation>导入SVG将清除当前画布上的所有内容。您想继续吗？</translation>
    </message>
    <message>
        <source>Import Successful</source>
        <translation>导入成功</translation>
    </message>
    <message>
        <source>SVG file has been imported successfully!</source>
        <translation>SVG文件已成功导入！</translation>
    </message>
    <message>
        <source>Import Failed</source>
        <translation>导入失败</translation>
    </message>
    <message>
        <source>An error occurred while importing the SVG file. Please ensure the file format is correct.</source>
        <translation>导入SVG文件时出错。请确保文件格式正确。</translation>
    </message>
    <message>
        <source>Number of shapes: 0</source>
        <translation>图形数量：0</translation>
    </message>
    <message>
        <source>Zoom level:100%</source>
        <translation>缩放比例：100%</translation>
    </message>
    <message>
        <source>Click to reset zoom</source>
        <translation>重置缩放</translation>
    </message>
    <message>
        <source>Number of shapes: %1</source>
        <translation>图形数量：%1</translation>
    </message>
    <message>
        <source>Zoom level: %1%</source>
        <translation>缩放比例：%1%</translation>
    </message>
    <message>
        <source>Select Fill Color</source>
        <translation>选择填充颜色</translation>
    </message>
    <message>
        <source>Select Line Color</source>
        <translation>选择线条颜色</translation>
    </message>
</context>
<context>
    <name>PageSettingDialog</name>
    <message>
        <source>Page Settings</source>
        <translation>页面设置</translation>
    </message>
    <message>
        <source>Page background color</source>
        <translation>页面背景颜色</translation>
    </message>
    <message>
        <source>Choose color...</source>
        <translation>选择颜色</translation>
    </message>
    <message>
        <source>Recently used colors</source>
        <translation>最近使用的颜色：</translation>
    </message>
    <message>
        <source>Current color:</source>
        <translation>当前颜色</translation>
    </message>
    <message>
        <source>Recently used:</source>
        <translation>最近使用：</translation>
    </message>
    <message>
        <source>Page size</source>
        <translation>页面尺寸</translation>
    </message>
    <message>
        <source>A3</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>A4</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>A5</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Default size</source>
        <translation>默认尺寸</translation>
    </message>
    <message>
        <source>Custom size</source>
        <translation>自定义尺寸</translation>
    </message>
    <message>
        <source> px</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Preset size:</source>
        <translation>预设尺寸：</translation>
    </message>
    <message>
        <source>Width:</source>
        <translation>宽：</translation>
    </message>
    <message>
        <source>Height:</source>
        <translation>高：</translation>
    </message>
    <message>
        <source>Page grid control</source>
        <translation>页面网格控制</translation>
    </message>
    <message>
        <source>Show grid</source>
        <translation>显示网格</translation>
    </message>
    <message>
        <source>Grid color...</source>
        <translation>网格颜色...</translation>
    </message>
    <message>
        <source>Small (10 px)</source>
        <translation>小</translation>
    </message>
    <message>
        <source>Normal (15 px)</source>
        <translation>正常</translation>
    </message>
    <message>
        <source>Large (25 px)</source>
        <translation>大</translation>
    </message>
    <message>
        <source>Very large (35 px)</source>
        <translation>很大</translation>
    </message>
    <message>
        <source>Very thin (0.5 px)</source>
        <translation>很细</translation>
    </message>
    <message>
        <source>Thin (1.5 px)</source>
        <translation>细</translation>
    </message>
    <message>
        <source>Normal (2 px)</source>
        <translation>正常</translation>
    </message>
    <message>
        <source>Thick (2.5 px)</source>
        <translation>粗</translation>
    </message>
    <message>
        <source>Very thick (3 px)</source>
        <translation>非常粗</translation>
    </message>
    <message>
        <source>Grid color:</source>
        <translation>网格颜色</translation>
    </message>
    <message>
        <source>Grid size:</source>
        <translation>网格尺寸</translation>
    </message>
    <message>
        <source>Line thickness:</source>
        <translation>线条粗细</translation>
    </message>
    <message>
        <source>OK</source>
        <translation>确定</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <source>Apply</source>
        <translation>应用</translation>
    </message>
    <message>
        <source>Current size: %1 x %2 px</source>
        <translation>目前大小：%1x%2 px</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Rectangle</source>
        <translation>矩形</translation>
    </message>
    <message>
        <source>Circle</source>
        <translation>圆形</translation>
    </message>
    <message>
        <source>Pentagon</source>
        <translation>五边形</translation>
    </message>
    <message>
        <source>Ellipse</source>
        <translation>椭圆形</translation>
    </message>
    <message>
        <source>Rounded Rectangle</source>
        <translation>圆角矩形</translation>
    </message>
    <message>
        <source>Diamond</source>
        <translation>菱形</translation>
    </message>
    <message>
        <source>Hexagon</source>
        <translation>六边形</translation>
    </message>
    <message>
        <source>Octagon</source>
        <translation>八边形</translation>
    </message>
    <message>
        <source>Cloud</source>
        <translation>云朵形</translation>
    </message>
    <message>
        <source>Font Color</source>
        <translation>字体颜色</translation>
    </message>
</context>
<context>
    <name>ShapeItem</name>
    <message>
        <source>Rectangle</source>
        <translation>矩形</translation>
    </message>
    <message>
        <source>Circle</source>
        <translation>圆形</translation>
    </message>
    <message>
        <source>Pentagon</source>
        <translation>五边形</translation>
    </message>
    <message>
        <source>Ellipse</source>
        <translation>椭圆形</translation>
    </message>
    <message>
        <source>ArrowLine</source>
        <translation>箭头</translation>
    </message>
    <message>
        <source>RoundedRectangle</source>
        <translation>圆角矩形</translation>
    </message>
    <message>
        <source>Diamond</source>
        <translation>菱形</translation>
    </message>
    <message>
        <source>Hexagon</source>
        <translation>六边形</translation>
    </message>
    <message>
        <source>Octagon</source>
        <translation>八边形</translation>
    </message>
    <message>
        <source>Cloud</source>
        <translation>云朵形</translation>
    </message>
</context>
<context>
    <name>ToolBar</name>
    <message>
        <source>Shape library</source>
        <translation>图形库</translation>
    </message>
    <message>
        <source>Please enter search content</source>
        <translation>请输入搜索内容</translation>
    </message>
    <message>
        <source>Basic shapes</source>
        <translation>基础形状</translation>
    </message>
    <message>
        <source>Flowchart</source>
        <translation>流程图形状</translation>
    </message>
</context>
</TS>
